apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swiftpay-prod

resources:
  - ../../base
  - ingress-traefik.yaml
  - vault-serviceaccount.yaml
  - vault-secret-store.yaml
  - vault-external-secrets.yaml

patches:
  - path: prod-config-patch.yaml
  - path: prod-env-patch.yaml
  - path: prod-scale-patch.yaml
  - path: prod-hpa-patch.yaml
  - path: prod-pdb-patch.yaml
  - path: prod-placement-patch.yaml
  - path: prod-probe-delays-patch.yaml
  - path: prod-db-migration-patch.yaml

labels:
  - pairs:
      environment: prod
      secret-source: vault
    includeSelectors: false

images:
  - name: veeno/api-gateway
    newName: swiftpay-api-gateway
    newTag: prod
  - name: veeno/auth-service
    newName: swiftpay-auth-service
    newTag: prod
  - name: veeno/frontend
    newName: swiftpay-frontend
    newTag: prod
  - name: veeno/notification-service
    newName: swiftpay-notification-service
    newTag: prod
  - name: veeno/transaction-service
    newName: swiftpay-transaction-service
    newTag: prod
  - name: veeno/wallet-service
    newName: swiftpay-wallet-service
    newTag: prod
